xmlrpcpp: Fix compilation warnings and use clang/rtti.
1. Fix couple of compiler warning generated by xmlrpcpp library.
2. Enable RTTI and CLANG in the makefile to be in line with Shill
test proxy compilation flags. The test proxy needs RTTI enabled since it
uses libchromeos which has has a few modules with RTTI features. So, 
this leads to "undefined reference to type_info" linker errors when 
linking against this xmlrpcpp library.

BUG: 24335496
Change-Id: Ieccdf577d04853e51933d25b774a6ef9fe2e7541
TEST: mmm external/xmlrpcpp